### ISSUE TITLE
Incorrect projection after changing "Impostor Type" to "Full Sphere View"

### ISSUE THREAD

**Issue by RomBinDaHouse** [ictusbrucks/ImpostorBaker#3]
and doing Clear RTs and Render Frames steps

**Comment by devonak** [comment]
Was this resolved because I can only get half sphere and billboard to work correctly.  Full sphere, even using clear RTs and then clicking render frames does not resolve the issue.  Looking at the maps generated it appears to function correctly up until rendering this in engine.
